#!/bin/sh

foldername="hubert_obrzut"
mkdir -p $foldername
mkdir -p $foldername/doc
mkdir -p $foldername/src

copy_ext_from_to() {
	from=$1
	ext=$2
	to=$3
	for file in $from/*.$ext; do
		cp $file $to
	done
}

copy_ext_from_to doc tex $foldername/doc
copy_ext_from_to doc pdf $foldername/doc
copy_ext_from_to src cpp $foldername/src
copy_ext_from_to src hpp $foldername/src

cp README.md $foldername
cp src/Makefile $foldername/src
cp src/merger $foldername/src

zip -r raport.zip $foldername
rm -rf $foldername
